PATTERN = (
    ("Key", "key"),
    ("File", "file"),
    ("Type", "type"),
    ("UsedInMainMenu", "used_in_main_menu"),
    ("NoTranslate", "no_translate"),
    ("KeepLoaded", "keep_loaded"),
    ("english", "english"),
    ("Context / Alternate Text", "context"),
    ("german", "german"),
    ("spanish", "spanish"),
    ("french", "french"),
    ("italian", "italian"),
    ("japanese", "japanese"),
    ("koreana", "koreana"),
    ("polish", "polish"),
    ("brazilian", "brazilian"),
    ("russian", "russian"),
    ("turkish", "turkish"),
    ("schinese", "schinese"),
    ("tchinese", "tchinese"),
)
